# version: '3.9'

# services:
#   web:
#     image: trainwithshubham/node-app:latest
#     ports:
#       - "8000:8000"

version: '3.9'

services:
  web:
    image: ghcr.io/rutvikmangukiya/node-todo-cicd:latest
    ports:
      - "8000:8000"

