name: CI - Docker Compose Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build services with Compose
      run: docker-compose build

    - name: Run app with Compose (detached)
      run: docker-compose up -d

    - name: Test app health
      run: |
        sleep 5
        curl -f http://localhost:8000 || (docker-compose logs && exit 1)

    - name: Security scan (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/node-todo-cicd:latest
        severity: HIGH,CRITICAL
        ignore-unfixed: true

    - name: Push image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/node-todo-cicd:latest
